# LilaKosha-MK1: Introspection & Recap-Augmentation Blueprint
pipeline:
    - "ingest-pippa"

project:
    name: "LilaKosha"
    mark: "MK1"
    generation: "G1"

volumes:
    raw: "${LILAKOSHA_VOLUME_RAW}"
    processed: "${LILAKOSHA_VOLUME_PROCESSED}"

parameters:
    limit: 2000 # limit the number of samples to process, if empty, all would be processed
