# LilaKosha-MK1: Introspection & Recap-Augmentation Blueprint
pipeline:
    - "ingest-pippa"
    - "report-cdm-records"

project:
    name: "LilaKosha"
    mark: "MK1"
    generation: "G1"

volumes:
    raw: "${LILAKOSHA_VOLUME_RAW}"
    processed: "${LILAKOSHA_VOLUME_PROCESSED}"

parameters:
    limit: 5 # used to test for major refactors
    # limit: 3000 # limit the number of samples to process, if empty, all would be processed
