# LilaKosha-MK1: Aggregate report on Document.items
pipeline:
    - "report-cdm"

project:
    name: "LilaKosha"
    mark: "MK1"
    generation: "G1"

volumes:
    processed: "${LILAKOSHA_VOLUME_PROCESSED}"

parameters:
    report_sections:
      - items
