# LilaKosha-MK1: Report on Character Names and Genders
pipeline:
    - "report-cdm"

project:
    name: "LilaKosha"
    mark: "MK1"
    generation: "G1"

volumes:
    processed: "${LILAKOSHA_VOLUME_PROCESSED}"

parameters:
    report_sections:
      - char_names
