# LilaKosha-MK1: Report on Record Health and Statistics
pipeline:
    - "report-record-health"

project:
    name: "LilaKosha"
    mark: "MK1"
    generation: "G1"

volumes:
    raw: "${LILAKOSHA_VOLUME_RAW}"
    processed: "${LILAKOSHA_VOLUME_PROCESSED}"
