# LilaKosha-MK1: Package CDM Dataset for Publish
pipeline:
    - "package"

project:
    name: "LilaKosha"
    mark: "MK1"
    generation: "G1"

volumes:
    processed: "${LILAKOSHA_VOLUME_PROCESSED}"
